/**
 * Maps the kebab-case glyph names stored in `categories.glyph` /
 * `wallets.glyph` onto Tabler components.
 *
 * The keys are deliberately unchanged from when this map pointed at Lucide.
 * They are data — 59 categories and a handful of wallets hold these strings —
 * so the visual refresh swaps the *values* and leaves the column alone. A few
 * keys therefore read as Lucide names for a Tabler glyph (`utensils` draws
 * `IconToolsKitchen2`); that is the price of not migrating rows to repaint a
 * screen, and it is the right trade.
 *
 * Explicit imports, not a dynamic lookup over the whole library, and the rule
 * is *stricter* here than it was: Lucide shipped 2025 icons and indexing its
 * namespace cost 180 kB gzipped — more than the whole initial bundle — while
 * Tabler ships 6 179. Never `import * as` this package. Adding a glyph means
 * adding a line here, which is the point: the set stays known.
 *
 * ## What the set costs
 *
 * **Every glyph in this map is in the initial chunk.** These are static
 * imports, so nothing here is loaded on demand — not the ones a picker only
 * ever offers, and not on the login screen either, which shares that chunk.
 * The map went from 111 keys to 256 and the initial bundle from 177 kB gzipped
 * to 189.5: **~86 bytes per glyph**, measured, which is the number to reach for
 * before growing it again. A few hundred is comfortable; a thousand is 86 kB
 * and would be the largest single thing the app ships.
 *
 * That is the whole reason the map is curated by hand rather than generated.
 * `iconFor` has to answer synchronously — a feed row's glyph comes out of the
 * database and is drawn on the same paint as the row — so there is no lazy
 * path available for the ones only the picker shows.
 */
import {
  IconAirConditioning,
  IconAlarm,
  IconAmbulance,
  IconArmchair,
  IconArrowBackUp,
  IconArrowBarToDown,
  IconArrowBarUp,
  IconArrowDown,
  IconArrowDownRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowsLeftRight,
  IconAward,
  IconBabyCarriage,
  IconBackpack,
  IconBackspace,
  IconBallBasketball,
  IconBallFootball,
  IconBalloon,
  IconBandage,
  IconBarbell,
  IconBarcode,
  IconBasket,
  IconBath,
  IconBattery,
  IconBeach,
  IconBed,
  IconBeer,
  IconBell,
  IconBike,
  IconBolt,
  IconBone,
  IconBook,
  IconBooks,
  IconBottle,
  IconBox,
  IconBrain,
  IconBread,
  IconBriefcase,
  IconBrush,
  IconBuilding,
  IconBuildingBank,
  IconBuildingChurch,
  IconBuildingCottage,
  IconBuildingHospital,
  IconBuildingStore,
  IconBulb,
  IconBurger,
  IconBus,
  IconCake,
  IconCalculator,
  IconCalendar,
  IconCalendarClock,
  IconCalendarEvent,
  IconCamera,
  IconCandy,
  IconCar,
  IconCarSuv,
  IconCash,
  IconCat,
  IconCategory,
  IconCertificate,
  IconChargingPile,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChecklist,
  IconCheese,
  IconChess,
  IconChevronLeft,
  IconChevronRight,
  IconCircle,
  IconCircleDashed,
  IconClock,
  IconCloud,
  IconCloudRain,
  IconCloudUpload,
  IconCoffee,
  IconCoin,
  IconCoins,
  IconCompass,
  IconConfetti,
  IconContract,
  IconCopy,
  IconCpu,
  IconCreditCard,
  IconCrown,
  IconCup,
  IconCurrencyBitcoin,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyPound,
  IconCurrencyZloty,
  IconDental,
  IconDeviceDesktop,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDeviceWatch,
  IconDiamond,
  IconDice,
  IconDiscount,
  IconDog,
  IconDoor,
  IconDots,
  IconDotsCircleHorizontal,
  IconDroplet,
  IconEgg,
  IconExchange,
  IconEyeglass,
  IconFileInvoice,
  IconFileText,
  IconFireExtinguisher,
  IconFirstAidKit,
  IconFish,
  IconFishHook,
  IconFlag,
  IconFlame,
  IconFlower,
  IconFridge,
  IconGasStation,
  IconGavel,
  IconGift,
  IconGiftCard,
  IconGlassFull,
  IconGripVertical,
  IconGuitarPick,
  IconHammer,
  IconHanger,
  IconHeadphones,
  IconHeart,
  IconHeartDollar,
  IconHeartHandshake,
  IconHeartbeat,
  IconHelmet,
  IconHelpCircle,
  IconHome,
  IconHourglass,
  IconIceCream,
  IconId,
  IconInfoCircle,
  IconKey,
  IconLamp,
  IconLeaf,
  IconLifebuoy,
  IconList,
  IconLock,
  IconLuggage,
  IconMail,
  IconMap2,
  IconMassage,
  IconMeat,
  IconMedal,
  IconMilk,
  IconMoneybag,
  IconMoodHappy,
  IconMoodKid,
  IconMoon,
  IconMotorbike,
  IconMountain,
  IconMovie,
  IconMusic,
  IconNotebook,
  IconNurse,
  IconPackage,
  IconPaint,
  IconPalette,
  IconParking,
  IconPaw,
  IconPencil,
  IconPercentage,
  IconPerfume,
  IconPhoneCall,
  IconPigMoney,
  IconPill,
  IconPizza,
  IconPlane,
  IconPlant2,
  IconPlug,
  IconPlus,
  IconPresentation,
  IconPrinter,
  IconPuzzle,
  IconReceipt,
  IconReceiptRefund,
  IconReceiptTax,
  IconRecycle,
  IconRepeat,
  IconReportMoney,
  IconRoad,
  IconRobot,
  IconRouter,
  IconRun,
  IconSalad,
  IconScale,
  IconSchool,
  IconScissors,
  IconScooter,
  IconScript,
  IconSearch,
  IconSelector,
  IconServer,
  IconShieldCheck,
  IconShip,
  IconShirt,
  IconShoe,
  IconShoppingBag,
  IconShoppingCart,
  IconSnowflake,
  IconSofa,
  IconSoup,
  IconSparkles,
  IconSpray,
  IconStar,
  IconSteeringWheel,
  IconStethoscope,
  IconSum,
  IconSun,
  IconSunglasses,
  IconSwimming,
  IconTag,
  IconTarget,
  IconTeapot,
  IconTent,
  IconTheater,
  IconTicket,
  IconTool,
  IconToolsKitchen2,
  IconTrain,
  IconTransfer,
  IconTrash,
  IconTree,
  IconTrendingDown,
  IconTrendingUp,
  IconTrophy,
  IconTruck,
  IconTruckDelivery,
  IconUmbrella,
  IconUrgent,
  IconUser,
  IconUsers,
  IconVaccine,
  IconVacuumCleaner,
  IconWalk,
  IconWallet,
  IconWashMachine,
  IconWheelchair,
  IconWifi,
  IconWorld,
  IconX,
  IconYoga,
} from '@tabler/icons-react'
import type { TablerIcon } from '@tabler/icons-react'

/** What every consumer types against, so the library name stays in this file. */
export type GlyphIcon = TablerIcon

export const ICONS: Record<string, GlyphIcon> = {
  'air-conditioning': IconAirConditioning,
  alarm: IconAlarm,
  ambulance: IconAmbulance,
  armchair: IconArmchair,
  'arrow-down': IconArrowDown,
  'arrow-down-right': IconArrowDownRight,
  'arrow-down-to-line': IconArrowBarToDown,
  'arrow-left-right': IconArrowsLeftRight,
  'arrow-up': IconArrowUp,
  'arrow-up-from-line': IconArrowBarUp,
  'arrow-up-right': IconArrowUpRight,
  award: IconAward,
  'baby-carriage': IconBabyCarriage,
  backpack: IconBackpack,
  backspace: IconBackspace,
  'ball-basketball': IconBallBasketball,
  'ball-football': IconBallFootball,
  balloon: IconBalloon,
  bandage: IconBandage,
  banknote: IconCash,
  barcode: IconBarcode,
  bath: IconBath,
  battery: IconBattery,
  beach: IconBeach,
  bed: IconBed,
  beer: IconBeer,
  bell: IconBell,
  bike: IconBike,
  bolt: IconBolt,
  bone: IconBone,
  'book-open': IconBook,
  books: IconBooks,
  bottle: IconBottle,
  box: IconBox,
  brain: IconBrain,
  briefcase: IconBriefcase,
  'briefcase-medical': IconFirstAidKit,
  brush: IconBrush,
  building: IconBuilding,
  'building-church': IconBuildingChurch,
  'building-cottage': IconBuildingCottage,
  'building-store': IconBuildingStore,
  bulb: IconBulb,
  burger: IconBurger,
  bus: IconBus,
  cake: IconCake,
  calculator: IconCalculator,
  calendar: IconCalendar,
  'calendar-clock': IconCalendarClock,
  'calendar-event': IconCalendarEvent,
  camera: IconCamera,
  candy: IconCandy,
  car: IconCar,
  // A second car silhouette rather than the same one twice: an icon is often the
  // only thing telling two feed rows apart, so a ride share must not draw what
  // `car` draws. Tabler has no taxi.
  'car-taxi-front': IconCarSuv,
  cat: IconCat,
  category: IconCategory,
  certificate: IconCertificate,
  'charging-pile': IconChargingPile,
  'chart-bar': IconChartBar,
  'chart-line': IconChartLine,
  'chart-pie': IconChartPie,
  check: IconCheck,
  checklist: IconChecklist,
  cheese: IconCheese,
  chess: IconChess,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  circle: IconCircle,
  'circle-dashed': IconCircleDashed,
  'circle-ellipsis': IconDotsCircleHorizontal,
  'circle-question-mark': IconHelpCircle,
  clock: IconClock,
  cloud: IconCloud,
  'cloud-rain': IconCloudRain,
  'cloud-upload': IconCloudUpload,
  coffee: IconCoffee,
  coin: IconCoin,
  compass: IconCompass,
  confetti: IconConfetti,
  contract: IconContract,
  copy: IconCopy,
  cpu: IconCpu,
  'credit-card': IconCreditCard,
  croissant: IconBread,
  crown: IconCrown,
  cup: IconCup,
  'currency-bitcoin': IconCurrencyBitcoin,
  'currency-dollar': IconCurrencyDollar,
  'currency-euro': IconCurrencyEuro,
  'currency-pound': IconCurrencyPound,
  'currency-zloty': IconCurrencyZloty,
  delete: IconBackspace,
  dental: IconDental,
  desktop: IconDeviceDesktop,
  diamond: IconDiamond,
  dice: IconDice,
  discount: IconDiscount,
  dog: IconDog,
  door: IconDoor,
  droplet: IconDroplet,
  dumbbell: IconBarbell,
  egg: IconEgg,
  ellipsis: IconDots,
  exchange: IconExchange,
  eyeglass: IconEyeglass,
  'file-text': IconFileText,
  'fire-extinguisher': IconFireExtinguisher,
  fish: IconFish,
  'fish-hook': IconFishHook,
  flag: IconFlag,
  flame: IconFlame,
  flower: IconFlower,
  fridge: IconFridge,
  'gamepad-2': IconDeviceGamepad2,
  'gas-station': IconGasStation,
  gavel: IconGavel,
  gift: IconGift,
  'gift-card': IconGiftCard,
  'graduation-cap': IconSchool,
  'grip-vertical': IconGripVertical,
  'guitar-pick': IconGuitarPick,
  hammer: IconHammer,
  'hand-coins': IconCoins,
  // "Giving money away" — the closest Tabler has to Lucide's hand cupping a
  // heart, and unambiguous next to `heart-handshake`.
  'hand-heart': IconHeartDollar,
  handshake: IconHeartHandshake,
  hanger: IconHanger,
  headphones: IconHeadphones,
  heart: IconHeart,
  'heart-handshake': IconHeartHandshake,
  'heart-pulse': IconHeartbeat,
  helmet: IconHelmet,
  hospital: IconBuildingHospital,
  hourglass: IconHourglass,
  house: IconHome,
  'ice-cream': IconIceCream,
  id: IconId,
  info: IconInfoCircle,
  'key-round': IconKey,
  lamp: IconLamp,
  landmark: IconBuildingBank,
  laptop: IconDeviceLaptop,
  leaf: IconLeaf,
  lifebuoy: IconLifebuoy,
  list: IconList,
  lock: IconLock,
  luggage: IconLuggage,
  mail: IconMail,
  map: IconMap2,
  massage: IconMassage,
  meat: IconMeat,
  medal: IconMedal,
  milk: IconMilk,
  moneybag: IconMoneybag,
  'mood-happy': IconMoodHappy,
  'mood-kid': IconMoodKid,
  moon: IconMoon,
  motorbike: IconMotorbike,
  mountain: IconMountain,
  movie: IconMovie,
  music: IconMusic,
  notebook: IconNotebook,
  nurse: IconNurse,
  package: IconPackage,
  paint: IconPaint,
  palette: IconPalette,
  parking: IconParking,
  'paw-print': IconPaw,
  pencil: IconPencil,
  percent: IconPercentage,
  perfume: IconPerfume,
  'phone-call': IconPhoneCall,
  'piggy-bank': IconPigMoney,
  pill: IconPill,
  pizza: IconPizza,
  plane: IconPlane,
  'plant-2': IconPlant2,
  plug: IconPlug,
  plus: IconPlus,
  presentation: IconPresentation,
  printer: IconPrinter,
  puzzle: IconPuzzle,
  receipt: IconReceipt,
  'receipt-refund': IconReceiptRefund,
  'receipt-tax': IconReceiptTax,
  'receipt-text': IconFileInvoice,
  recycle: IconRecycle,
  repeat: IconRepeat,
  'report-money': IconReportMoney,
  road: IconRoad,
  robot: IconRobot,
  router: IconRouter,
  run: IconRun,
  salad: IconSalad,
  scale: IconScale,
  scissors: IconScissors,
  scooter: IconScooter,
  scroll: IconScript,
  search: IconSearch,
  selector: IconSelector,
  server: IconServer,
  'shield-check': IconShieldCheck,
  ship: IconShip,
  shirt: IconShirt,
  shoe: IconShoe,
  'shopping-bag': IconShoppingBag,
  'shopping-basket': IconBasket,
  'shopping-cart': IconShoppingCart,
  sigma: IconSum,
  siren: IconUrgent,
  smartphone: IconDeviceMobile,
  snowflake: IconSnowflake,
  sofa: IconSofa,
  soup: IconSoup,
  sparkles: IconSparkles,
  spray: IconSpray,
  star: IconStar,
  'steering-wheel': IconSteeringWheel,
  stethoscope: IconStethoscope,
  sun: IconSun,
  sunglasses: IconSunglasses,
  swimming: IconSwimming,
  tag: IconTag,
  target: IconTarget,
  teapot: IconTeapot,
  tent: IconTent,
  theater: IconTheater,
  ticket: IconTicket,
  tool: IconTool,
  train: IconTrain,
  transfer: IconTransfer,
  'trash-2': IconTrash,
  tree: IconTree,
  'trending-down': IconTrendingDown,
  'trending-up': IconTrendingUp,
  trophy: IconTrophy,
  truck: IconTruck,
  'truck-delivery': IconTruckDelivery,
  tv: IconDeviceTv,
  umbrella: IconUmbrella,
  'undo-2': IconArrowBackUp,
  'user-round': IconUser,
  'users-round': IconUsers,
  utensils: IconToolsKitchen2,
  vaccine: IconVaccine,
  'vacuum-cleaner': IconVacuumCleaner,
  walk: IconWalk,
  wallet: IconWallet,
  'wash-machine': IconWashMachine,
  watch: IconDeviceWatch,
  wheelchair: IconWheelchair,
  wifi: IconWifi,
  wine: IconGlassFull,
  world: IconWorld,
  x: IconX,
  yoga: IconYoga,
  zap: IconBolt,
}

/** Falls back to a neutral mark rather than rendering nothing for a typo. */
export const iconFor = (name: string | null | undefined): GlyphIcon =>
  (name && ICONS[name]) || IconCircle

/**
 * App chrome, filtered out of the pickers: nobody wants a chevron for their
 * groceries, and a glyph that also means "close" or "drag me" reads as a
 * control rather than a subject.
 */
const CHROME = new Set([
  'arrow-down-right',
  'arrow-up-right',
  'backspace',
  'check',
  'chevron-left',
  'chevron-right',
  'circle-dashed',
  'delete',
  'ellipsis',
  'grip-vertical',
  'search',
  'selector',
  'x',
])

/**
 * The glyphs a picker shows first.
 *
 * `Object.keys` is alphabetical, which put five arrows and a banknote at the
 * head — the picker's first row was the least likely thing anyone wanted. These
 * are the everyday subjects instead: what people actually spend money on, in
 * rough order of how often a category needs them. Everything else follows
 * alphabetically, and the search field reaches all of it.
 */
const COMMON = [
  // The first eighteen are the preview grid, so they are the ones that have to
  // be right; the rest of this list is the screenful after it.
  'shopping-basket',
  'utensils',
  'coffee',
  'car',
  'house',
  'bus',
  'shopping-bag',
  'heart-pulse',
  'gift',
  'plane',
  'ticket',
  'smartphone',
  'shirt',
  'dumbbell',
  'paw-print',
  'graduation-cap',
  'briefcase',
  'piggy-bank',
  'credit-card',
  'banknote',
  'users-round',
  'repeat',
  'zap',
  'receipt',
  'pizza',
  'burger',
  'beer',
  'wine',
  'gas-station',
  'train',
  'bike',
  'parking',
  'bed',
  'bulb',
  'droplet',
  'flame',
  'wash-machine',
  'laptop',
  'headphones',
  'movie',
  'music',
  'tv',
  'stethoscope',
  'pill',
  'dental',
  'baby-carriage',
  'dog',
  'cat',
  'building-store',
  'truck-delivery',
  'luggage',
  'beach',
  'ball-football',
  'scissors',
  'perfume',
  'chart-line',
  'coin',
  'moneybag',
  'receipt-tax',
  'contract',
  'star',
]

export const GLYPH_CHOICES = [
  ...COMMON.filter((n) => n in ICONS),
  ...Object.keys(ICONS).filter((n) => !CHROME.has(n) && !COMMON.includes(n)),
]
