/**
 * Maps the kebab-case glyph names stored in `categories.glyph` /
 * `wallets.glyph` onto Lucide components.
 *
 * Explicit imports, not a dynamic lookup over the whole library: Lucide ships
 * 2025 icons, and indexing into the namespace defeats tree-shaking — measured at
 * 180 kB gzipped, more than the whole initial bundle. Adding a glyph means adding
 * a line here, which is the point — the set stays known, and costs ~90 bytes
 * gzipped each.
 *
 * `lucide-react/dynamic` would lift the ceiling for ~14 kB plus a request per
 * icon, if a fixed list ever stops being enough.
 */
import {
  ArrowDown,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpFromLine,
  Banknote,
  BookOpen,
  Brain,
  Briefcase,
  BriefcaseMedical,
  Bus,
  Calculator,
  Calendar,
  CalendarClock,
  Car,
  CarTaxiFront,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleEllipsis,
  CircleQuestionMark,
  Coffee,
  Copy,
  Cpu,
  CreditCard,
  Croissant,
  Delete,
  Dumbbell,
  Ellipsis,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  House,
  Info,
  KeyRound,
  Landmark,
  List,
  Lock,
  Package,
  PawPrint,
  Pencil,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  ReceiptText,
  Repeat,
  Salad,
  Scissors,
  Scroll,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sigma,
  Siren,
  Smartphone,
  Target,
  Tag,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  Umbrella,
  Undo2,
  UserRound,
  UsersRound,
  Utensils,
  Wallet,
  Wifi,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  'arrow-down': ArrowDown,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up': ArrowUp,
  'arrow-up-from-line': ArrowUpFromLine,
  banknote: Banknote,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  'briefcase-medical': BriefcaseMedical,
  bus: Bus,
  calculator: Calculator,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  car: Car,
  'car-taxi-front': CarTaxiFront,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-ellipsis': CircleEllipsis,
  // Lucide also ships `circle-help` for this glyph, but that module is a
  // deprecated alias with no icon data of its own — use the canonical name.
  'circle-question-mark': CircleQuestionMark,
  coffee: Coffee,
  copy: Copy,
  cpu: Cpu,
  'credit-card': CreditCard,
  croissant: Croissant,
  delete: Delete,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  handshake: Handshake,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  house: House,
  info: Info,
  'key-round': KeyRound,
  landmark: Landmark,
  list: List,
  lock: Lock,
  package: Package,
  'paw-print': PawPrint,
  pencil: Pencil,
  percent: Percent,
  'piggy-bank': PiggyBank,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  repeat: Repeat,
  salad: Salad,
  scissors: Scissors,
  scroll: Scroll,
  search: Search,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  sigma: Sigma,
  siren: Siren,
  smartphone: Smartphone,
  tag: Tag,
  target: Target,
  ticket: Ticket,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  umbrella: Umbrella,
  'undo-2': Undo2,
  'user-round': UserRound,
  'users-round': UsersRound,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  x: X,
  zap: Zap,
}

/** Falls back to a neutral mark rather than rendering nothing for a typo. */
export const iconFor = (name: string | null | undefined): LucideIcon =>
  (name && ICONS[name]) || Circle

/** Names offered in pickers, in a sensible browsing order. */
export const GLYPH_CHOICES = Object.keys(ICONS).filter(
  (n) => !['chevron-left', 'chevron-right', 'x', 'check', 'ellipsis', 'search', 'delete'].includes(n),
)
